ARG BASE_IMAGE

FROM $BASE_IMAGE as build_output
LABEL maintainer="morteza.alizadeh@gmail.com"

FROM microbusiness/firebase-toolset:0.1.1

ARG FIREBASE_TOKEN
ARG FIREBASE_PROJECT_ID

RUN mkdir /src
COPY --from=build_output /src /src

WORKDIR /src
RUN firebase deploy --only functions --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT_ID
